# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `guard-shell` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Guard
  extend ::Guard::Deprecated::Guard::ClassMethods
  extend ::Guard::Internals::Helpers

  class << self
    def async_queue_add(changes); end
    def init(cmdline_options); end
    def interactor; end
    def listener; end
    def queue; end
    def setup(cmdline_options = T.unsafe(nil)); end
    def state; end

    private

    def _evaluate(options); end
    def _guardfile_deprecated_check(modified); end
    def _listener_callback; end
    def _pluginless_guardfile?; end
    def _relative_pathnames(paths); end
    def _relevant_changes?(changes); end
  end
end

class Guard::Dsl
  extend ::Guard::Deprecated::Dsl::ClassMethods

  def callback(*args, &block); end
  def clearing(on); end
  def directories(directories); end
  def eager(command); end
  def evaluate(contents, filename, lineno); end
  def filter(*regexps); end
  def filter!(*regexps); end
  def group(*args); end
  def guard(name, options = T.unsafe(nil)); end
  def ignore(*regexps); end
  def ignore!(*regexps); end
  def interactor(options); end
  def logger(options); end
  def n(msg, title = T.unsafe(nil), image = T.unsafe(nil)); end
  def notification(notifier, opts = T.unsafe(nil)); end
  def scope(scope = T.unsafe(nil)); end
  def watch(pattern, &action); end

  private

  def _cleanup_backtrace(backtrace); end
end

Guard::Dsl::WARN_INVALID_LOG_LEVEL = T.let(T.unsafe(nil), String)
Guard::Dsl::WARN_INVALID_LOG_OPTIONS = T.let(T.unsafe(nil), String)

class Guard::Shell < ::Guard::Plugin
  def available_watchers; end
  def run_all; end
  def run_on_modifications(res); end
  def start; end
  def stop; end
end

module Guard::ShellVersion; end
Guard::ShellVersion::VERSION = T.let(T.unsafe(nil), String)
