# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `path_expander` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class PathExpander
  def initialize(args, glob, path = T.unsafe(nil)); end

  def args; end
  def args=(_arg0); end
  def expand_dirs_to_files(*dirs); end
  def filter_files(files, ignore); end
  def glob; end
  def glob=(_arg0); end
  def path; end
  def path=(_arg0); end
  def process; end
  def process_args; end
  def process_file(path); end
  def process_flags(flags); end
end

PathExpander::VERSION = T.let(T.unsafe(nil), String)
