# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `reline` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Reline
  extend ::Forwardable
  extend ::SingleForwardable

  def eof?(*args, &block); end

  private

  def readline(*args, &block); end
  def readmultiline(*args, &block); end

  class << self
    def ambiguous_width(*args, &block); end
    def auto_indent_proc(*args, &block); end
    def auto_indent_proc=(*args, &block); end
    def basic_quote_characters(*args, &block); end
    def basic_quote_characters=(*args, &block); end
    def basic_word_break_characters(*args, &block); end
    def basic_word_break_characters=(*args, &block); end
    def completer_quote_characters(*args, &block); end
    def completer_quote_characters=(*args, &block); end
    def completer_word_break_characters(*args, &block); end
    def completer_word_break_characters=(*args, &block); end
    def completion_append_character(*args, &block); end
    def completion_append_character=(*args, &block); end
    def completion_case_fold(*args, &block); end
    def completion_case_fold=(*args, &block); end
    def completion_proc(*args, &block); end
    def completion_proc=(*args, &block); end
    def completion_quote_character(*args, &block); end
    def core; end
    def delete_text(*args, &block); end
    def dig_perfect_match_proc(*args, &block); end
    def dig_perfect_match_proc=(*args, &block); end
    def emacs_editing_mode(*args, &block); end
    def emacs_editing_mode?(*args, &block); end
    def encoding_system_needs; end
    def eof?(*args, &block); end
    def filename_quote_characters(*args, &block); end
    def filename_quote_characters=(*args, &block); end
    def get_screen_size(*args, &block); end
    def input=(*args, &block); end
    def insert_text(*args, &block); end
    def last_incremental_search(*args, &block); end
    def last_incremental_search=(*args, &block); end
    def line_buffer(*args, &block); end
    def line_editor; end
    def output=(*args, &block); end
    def output_modifier_proc(*args, &block); end
    def output_modifier_proc=(*args, &block); end
    def point(*args, &block); end
    def point=(*args, &block); end
    def pre_input_hook(*args, &block); end
    def pre_input_hook=(*args, &block); end
    def prompt_proc(*args, &block); end
    def prompt_proc=(*args, &block); end
    def readline(*args, &block); end
    def readmultiline(*args, &block); end
    def redisplay(*args, &block); end
    def special_prefixes(*args, &block); end
    def special_prefixes=(*args, &block); end
    def ungetc(c); end
    def vi_editing_mode(*args, &block); end
    def vi_editing_mode?(*args, &block); end
  end
end

class Reline::ANSI
  class << self
    def clear_screen; end
    def cursor_pos; end
    def deprep(otio); end
    def empty_buffer?; end
    def encoding; end
    def erase_after_cursor; end
    def get_screen_size; end
    def getc; end
    def getc_with_bracketed_paste; end
    def in_pasting?; end
    def inner_getc; end
    def input=(val); end
    def move_cursor_column(x); end
    def move_cursor_down(x); end
    def move_cursor_up(x); end
    def output=(val); end
    def prep; end
    def retrieve_keybuffer; end
    def scroll_down(x); end
    def set_default_key_bindings(config); end
    def set_default_key_bindings_comprehensive_list(config); end
    def set_default_key_bindings_terminfo(config); end
    def set_screen_size(rows, columns); end
    def set_winch_handler(&handler); end
    def ungetc(c); end
    def win?; end
  end
end

Reline::ANSI::END_BRACKETED_PASTE = T.let(T.unsafe(nil), String)
Reline::ANSI::START_BRACKETED_PASTE = T.let(T.unsafe(nil), String)

class Reline::Config
  def initialize; end

  def add_default_key_binding(keystroke, target); end
  def add_default_key_binding_by_keymap(keymap, keystroke, target); end
  def bind_key(key, func_name); end
  def bind_tty_special_chars; end
  def bind_tty_special_chars=(_arg0); end
  def bind_variable(name, value); end
  def blink_matching_paren; end
  def blink_matching_paren=(_arg0); end
  def byte_oriented; end
  def byte_oriented=(_arg0); end
  def completion_ignore_case; end
  def completion_ignore_case=(_arg0); end
  def convert_meta; end
  def convert_meta=(_arg0); end
  def disable_completion; end
  def disable_completion=(_arg0); end
  def editing_mode; end
  def editing_mode=(val); end
  def editing_mode_is?(*val); end
  def emacs_mode_string; end
  def emacs_mode_string=(_arg0); end
  def enable_bracketed_paste; end
  def enable_bracketed_paste=(_arg0); end
  def enable_keypad; end
  def enable_keypad=(_arg0); end
  def expand_tilde; end
  def expand_tilde=(_arg0); end
  def handle_directive(directive, file, no); end
  def history_preserve_point; end
  def history_preserve_point=(_arg0); end
  def history_size; end
  def history_size=(_arg0); end
  def horizontal_scroll_mode; end
  def horizontal_scroll_mode=(_arg0); end
  def input_meta; end
  def input_meta=(_arg0); end
  def inputrc_path; end
  def isearch_terminators; end
  def isearch_terminators=(_arg0); end
  def key_bindings; end
  def key_notation_to_code(notation); end
  def keymap; end
  def keyseq_timeout; end
  def keyseq_timeout=(_arg0); end
  def mark_directories; end
  def mark_directories=(_arg0); end
  def mark_modified_lines; end
  def mark_modified_lines=(_arg0); end
  def mark_symlinked_directories; end
  def mark_symlinked_directories=(_arg0); end
  def match_hidden_files; end
  def match_hidden_files=(_arg0); end
  def meta_flag; end
  def meta_flag=(_arg0); end
  def output_meta; end
  def output_meta=(_arg0); end
  def page_completions; end
  def page_completions=(_arg0); end
  def parse_keyseq(str); end
  def prefer_visible_bell; end
  def prefer_visible_bell=(_arg0); end
  def print_completions_horizontally; end
  def print_completions_horizontally=(_arg0); end
  def read(file = T.unsafe(nil)); end
  def read_lines(lines, file = T.unsafe(nil)); end
  def reset; end
  def reset_default_key_bindings; end
  def retrieve_string(str); end
  def show_all_if_ambiguous; end
  def show_all_if_ambiguous=(_arg0); end
  def show_all_if_unmodified; end
  def show_all_if_unmodified=(_arg0); end
  def show_mode_in_prompt; end
  def show_mode_in_prompt=(_arg0); end
  def test_mode; end
  def vi_cmd_mode_string; end
  def vi_cmd_mode_string=(_arg0); end
  def vi_ins_mode_string; end
  def vi_ins_mode_string=(_arg0); end
  def visible_stats; end
  def visible_stats=(_arg0); end
end

class Reline::Config::InvalidInputrc < ::RuntimeError
  def file; end
  def file=(_arg0); end
  def lineno; end
  def lineno=(_arg0); end
end

Reline::Config::KEYSEQ_PATTERN = T.let(T.unsafe(nil), Regexp)
Reline::Config::VARIABLE_NAMES = T.let(T.unsafe(nil), Array)
Reline::Config::VARIABLE_NAME_SYMBOLS = T.let(T.unsafe(nil), Array)

class Reline::Core
  def initialize; end

  def ambiguous_width; end
  def auto_indent_proc; end
  def auto_indent_proc=(p); end
  def basic_quote_characters; end
  def basic_quote_characters=(v); end
  def basic_word_break_characters; end
  def basic_word_break_characters=(v); end
  def completer_quote_characters; end
  def completer_quote_characters=(v); end
  def completer_word_break_characters; end
  def completer_word_break_characters=(v); end
  def completion_append_character; end
  def completion_append_character=(val); end
  def completion_case_fold; end
  def completion_case_fold=(v); end
  def completion_proc; end
  def completion_proc=(p); end
  def completion_quote_character; end
  def config; end
  def config=(_arg0); end
  def dig_perfect_match_proc; end
  def dig_perfect_match_proc=(p); end
  def emacs_editing_mode; end
  def emacs_editing_mode?; end
  def encoding; end
  def filename_quote_characters; end
  def filename_quote_characters=(v); end
  def get_screen_size; end
  def input=(val); end
  def key_stroke; end
  def key_stroke=(_arg0); end
  def last_incremental_search; end
  def last_incremental_search=(_arg0); end
  def line_editor; end
  def line_editor=(_arg0); end
  def output; end
  def output=(val); end
  def output_modifier_proc; end
  def output_modifier_proc=(p); end
  def pre_input_hook; end
  def pre_input_hook=(p); end
  def prompt_proc; end
  def prompt_proc=(p); end
  def readline(prompt = T.unsafe(nil), add_hist = T.unsafe(nil)); end
  def readmultiline(prompt = T.unsafe(nil), add_hist = T.unsafe(nil), &confirm_multiline_termination); end
  def special_prefixes; end
  def special_prefixes=(v); end
  def vi_editing_mode; end
  def vi_editing_mode?; end

  private

  def inner_readline(prompt, add_hist, multiline, &confirm_multiline_termination); end
  def may_req_ambiguous_char_width; end
  def read_escaped_key(keyseq_timeout, c, block); end
  def read_io(keyseq_timeout, &block); end
end

Reline::Core::ATTR_READER_NAMES = T.let(T.unsafe(nil), Array)

class Reline::CursorPos < ::Struct
  def x; end
  def x=(_); end
  def y; end
  def y=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

class Reline::GeneralIO
  class << self
    def clear_screen; end
    def cursor_pos; end
    def deprep(otio); end
    def encoding; end
    def erase_after_cursor; end
    def finish_pasting; end
    def get_screen_size; end
    def getc; end
    def in_pasting?; end
    def input=(val); end
    def move_cursor_column(val); end
    def move_cursor_down(val); end
    def move_cursor_up(val); end
    def prep; end
    def reset(encoding: T.unsafe(nil)); end
    def scroll_down(val); end
    def set_default_key_bindings(_); end
    def set_screen_size(rows, columns); end
    def set_winch_handler(&handler); end
    def start_pasting; end
    def ungetc(c); end
    def win?; end
  end
end

Reline::HISTORY = T.let(T.unsafe(nil), Reline::History)

class Reline::History < ::Array
  def initialize(config); end

  def <<(val); end
  def [](index); end
  def []=(index, val); end
  def concat(*val); end
  def delete_at(index); end
  def push(*val); end
  def to_s; end

  private

  def check_index(index); end
end

Reline::IOGate = Reline::ANSI
Reline::Key = Struct
module Reline::KeyActor; end

class Reline::KeyActor::Base
  def initialize; end

  def default_key_bindings; end
  def get_method(key); end
  def reset_default_key_bindings; end
end

Reline::KeyActor::Base::MAPPING = T.let(T.unsafe(nil), Array)
class Reline::KeyActor::Emacs < ::Reline::KeyActor::Base; end
Reline::KeyActor::Emacs::MAPPING = T.let(T.unsafe(nil), Array)
class Reline::KeyActor::ViCommand < ::Reline::KeyActor::Base; end
Reline::KeyActor::ViCommand::MAPPING = T.let(T.unsafe(nil), Array)
class Reline::KeyActor::ViInsert < ::Reline::KeyActor::Base; end
Reline::KeyActor::ViInsert::MAPPING = T.let(T.unsafe(nil), Array)

class Reline::KeyStroke
  def initialize(config); end

  def expand(input); end
  def match_status(input); end

  private

  def key_mapping; end
end

class Reline::KillRing
  include ::Enumerable

  def initialize(max = T.unsafe(nil)); end

  def append(string, before_p = T.unsafe(nil)); end
  def each; end
  def process; end
  def yank; end
  def yank_pop; end
end

class Reline::KillRing::RingBuffer
  def initialize(max = T.unsafe(nil)); end

  def <<(point); end
  def empty?; end
  def head; end
  def size; end
end

class Reline::KillRing::RingPoint < ::Struct
  def initialize(str); end

  def ==(other); end
  def backward; end
  def backward=(_); end
  def forward; end
  def forward=(_); end
  def str; end
  def str=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

module Reline::KillRing::State; end
Reline::KillRing::State::CONTINUED = T.let(T.unsafe(nil), Symbol)
Reline::KillRing::State::FRESH = T.let(T.unsafe(nil), Symbol)
Reline::KillRing::State::PROCESSED = T.let(T.unsafe(nil), Symbol)
Reline::KillRing::State::YANK = T.let(T.unsafe(nil), Symbol)

class Reline::LineEditor
  def initialize(config, encoding); end

  def auto_indent_proc; end
  def auto_indent_proc=(_arg0); end
  def byte_pointer; end
  def byte_pointer=(val); end
  def call_completion_proc; end
  def completion_append_character; end
  def completion_append_character=(_arg0); end
  def completion_proc; end
  def completion_proc=(_arg0); end
  def confirm_multiline_termination; end
  def confirm_multiline_termination_proc; end
  def confirm_multiline_termination_proc=(_arg0); end
  def delete_text(start = T.unsafe(nil), length = T.unsafe(nil)); end
  def dig_perfect_match_proc; end
  def dig_perfect_match_proc=(_arg0); end
  def editing_mode; end
  def eof?; end
  def finalize; end
  def finish; end
  def finished?; end
  def input_key(key); end
  def insert_text(text); end
  def just_move_cursor; end
  def line; end
  def multiline_off; end
  def multiline_on; end
  def output=(_arg0); end
  def output_modifier_proc; end
  def output_modifier_proc=(_arg0); end
  def pre_input_hook; end
  def pre_input_hook=(_arg0); end
  def prompt_proc; end
  def prompt_proc=(_arg0); end
  def rerender; end
  def rerender_all; end
  def reset(prompt = T.unsafe(nil), encoding:); end
  def reset_line; end
  def reset_variables(prompt = T.unsafe(nil), encoding:); end
  def retrieve_completion_block(set_completion_quote_character = T.unsafe(nil)); end
  def set_pasting_state(in_pasting); end
  def simplified_rendering?; end
  def whole_buffer; end
  def whole_lines(index: T.unsafe(nil), line: T.unsafe(nil)); end
  def wrap_method_call(method_symbol, method_obj, key, with_operator = T.unsafe(nil)); end

  private

  def argumentable?(method_obj); end
  def backward_char(key, arg: T.unsafe(nil)); end
  def backward_delete_char(key); end
  def backward_word(key); end
  def beginning_of_line(key); end
  def byteinsert(str, byte_pointer, other); end
  def byteslice!(str, byte_pointer, size); end
  def calculate_height_by_lines(lines, prompt); end
  def calculate_height_by_width(width); end
  def calculate_nearest_cursor(line_to_calc = T.unsafe(nil), cursor = T.unsafe(nil), started_from = T.unsafe(nil), byte_pointer = T.unsafe(nil), update = T.unsafe(nil)); end
  def calculate_scroll_partial_screen(highest_in_all, cursor_y); end
  def calculate_width(str, allow_escape_code = T.unsafe(nil)); end
  def capitalize_word(key); end
  def check_mode_string; end
  def check_multiline_prompt(buffer, prompt); end
  def clear_screen(key); end
  def clear_screen_buffer(prompt, prompt_list, prompt_width); end
  def complete(list, just_show_list = T.unsafe(nil)); end
  def complete_internal_proc(list, is_menu); end
  def copy_for_vi(text); end
  def delete_char(key); end
  def delete_char_or_list(key); end
  def downcase_word(key); end
  def ed_argument_digit(key); end
  def ed_clear_screen(key); end
  def ed_delete_next_char(key, arg: T.unsafe(nil)); end
  def ed_delete_prev_char(key, arg: T.unsafe(nil)); end
  def ed_delete_prev_word(key); end
  def ed_digit(key); end
  def ed_insert(key); end
  def ed_kill_line(key); end
  def ed_move_to_beg(key); end
  def ed_move_to_end(key); end
  def ed_newline(key); end
  def ed_next_char(key, arg: T.unsafe(nil)); end
  def ed_next_history(key, arg: T.unsafe(nil)); end
  def ed_prev_char(key, arg: T.unsafe(nil)); end
  def ed_prev_history(key, arg: T.unsafe(nil)); end
  def ed_prev_word(key); end
  def ed_quoted_insert(str, arg: T.unsafe(nil)); end
  def ed_search_next_history(key, arg: T.unsafe(nil)); end
  def ed_search_prev_history(key, arg: T.unsafe(nil)); end
  def ed_transpose_chars(key); end
  def ed_transpose_words(key); end
  def ed_unassigned(key); end
  def em_capitol_case(key); end
  def em_delete(key); end
  def em_delete_next_word(key); end
  def em_delete_or_list(key); end
  def em_delete_prev_char(key); end
  def em_exchange_mark(key); end
  def em_kill_line(key); end
  def em_kill_region(key); end
  def em_lower_case(key); end
  def em_next_word(key); end
  def em_set_mark(key); end
  def em_upper_case(key); end
  def em_yank(key); end
  def em_yank_pop(key); end
  def end_of_line(key); end
  def exchange_point_and_mark(key); end
  def forward_char(key, arg: T.unsafe(nil)); end
  def forward_search_history(key); end
  def forward_word(key); end
  def generate_searcher; end
  def history_search_backward(key, arg: T.unsafe(nil)); end
  def history_search_forward(key, arg: T.unsafe(nil)); end
  def inclusive?(method_obj); end
  def incremental_search_history(key); end
  def insert_new_line(cursor_line, next_line); end
  def key_delete(key); end
  def key_newline(key); end
  def kill_line(key); end
  def menu(target, list); end
  def modify_lines(before); end
  def move_completed_list(list, direction); end
  def move_cursor_down(val); end
  def move_cursor_up(val); end
  def normal_char(key); end
  def process_auto_indent; end
  def process_insert(force: T.unsafe(nil)); end
  def process_key(key, method_symbol); end
  def quoted_insert(str, arg: T.unsafe(nil)); end
  def render_partial(prompt, prompt_width, line_to_render, this_started_from, with_control: T.unsafe(nil)); end
  def render_whole_lines(lines, prompt, prompt_width); end
  def rerender_added_newline(prompt, prompt_width); end
  def rerender_all_lines; end
  def rerender_changed_current_line; end
  def reverse_search_history(key); end
  def run_for_operators(key, method_symbol, &block); end
  def scroll_down(val); end
  def search_next_char(key, arg, need_prev_char: T.unsafe(nil), inclusive: T.unsafe(nil)); end
  def search_prev_char(key, arg, need_next_char = T.unsafe(nil)); end
  def self_insert(key); end
  def set_mark(key); end
  def show_menu; end
  def split_by_width(str, max_width); end
  def transpose_chars(key); end
  def transpose_words(key); end
  def unix_word_rubout(key); end
  def upcase_word(key); end
  def vi_add(key); end
  def vi_add_at_eol(key); end
  def vi_change_meta(key, arg: T.unsafe(nil)); end
  def vi_command_mode(key); end
  def vi_delete_meta(key, arg: T.unsafe(nil)); end
  def vi_delete_prev_char(key); end
  def vi_end_big_word(key, arg: T.unsafe(nil), inclusive: T.unsafe(nil)); end
  def vi_end_of_transmission(key); end
  def vi_end_word(key, arg: T.unsafe(nil), inclusive: T.unsafe(nil)); end
  def vi_eof_maybe(key); end
  def vi_first_print(key); end
  def vi_histedit(key); end
  def vi_insert(key); end
  def vi_insert_at_bol(key); end
  def vi_join_lines(key, arg: T.unsafe(nil)); end
  def vi_list_or_eof(key); end
  def vi_movement_mode(key); end
  def vi_next_big_word(key, arg: T.unsafe(nil)); end
  def vi_next_char(key, arg: T.unsafe(nil), inclusive: T.unsafe(nil)); end
  def vi_next_word(key, arg: T.unsafe(nil)); end
  def vi_paste_next(key, arg: T.unsafe(nil)); end
  def vi_paste_prev(key, arg: T.unsafe(nil)); end
  def vi_prev_big_word(key, arg: T.unsafe(nil)); end
  def vi_prev_char(key, arg: T.unsafe(nil)); end
  def vi_prev_word(key, arg: T.unsafe(nil)); end
  def vi_replace_char(key, arg: T.unsafe(nil)); end
  def vi_search_next(key); end
  def vi_search_prev(key); end
  def vi_to_column(key, arg: T.unsafe(nil)); end
  def vi_to_history_line(key); end
  def vi_to_next_char(key, arg: T.unsafe(nil), inclusive: T.unsafe(nil)); end
  def vi_to_prev_char(key, arg: T.unsafe(nil)); end
  def vi_yank(key, arg: T.unsafe(nil)); end
  def vi_zero(key); end
  def yank(key); end
  def yank_pop(key); end
end

Reline::LineEditor::CompletionJourneyData = Struct
module Reline::LineEditor::CompletionState; end
Reline::LineEditor::CompletionState::COMPLETION = T.let(T.unsafe(nil), Symbol)
Reline::LineEditor::CompletionState::JOURNEY = T.let(T.unsafe(nil), Symbol)
Reline::LineEditor::CompletionState::MENU = T.let(T.unsafe(nil), Symbol)
Reline::LineEditor::CompletionState::MENU_WITH_PERFECT_MATCH = T.let(T.unsafe(nil), Symbol)
Reline::LineEditor::CompletionState::NORMAL = T.let(T.unsafe(nil), Symbol)
Reline::LineEditor::CompletionState::PERFECT_MATCH = T.let(T.unsafe(nil), Symbol)
Reline::LineEditor::MenuInfo = Struct
Reline::LineEditor::PROMPT_LIST_CACHE_TIMEOUT = T.let(T.unsafe(nil), Float)
Reline::LineEditor::VI_MOTIONS = T.let(T.unsafe(nil), Array)

module Reline::Terminfo
  extend ::Fiddle
  extend ::Fiddle::CParser
  extend ::Fiddle::Importer

  class << self
    def curses_dl; end
    def enabled?; end
  end
end

class Reline::Terminfo::TerminfoError < ::StandardError; end

class Reline::Unicode
  class << self
    def calculate_width(str, allow_escape_code = T.unsafe(nil)); end
    def ed_transpose_words(line, byte_pointer); end
    def em_backward_word(line, byte_pointer); end
    def em_big_backward_word(line, byte_pointer); end
    def em_forward_word(line, byte_pointer); end
    def em_forward_word_with_capitalization(line, byte_pointer); end
    def escape_for_print(str); end
    def get_mbchar_byte_size_by_first_char(c); end
    def get_mbchar_width(mbchar); end
    def get_next_mbchar_size(line, byte_pointer); end
    def get_prev_mbchar_size(line, byte_pointer); end
    def split_by_width(str, max_width, encoding = T.unsafe(nil)); end
    def vi_backward_word(line, byte_pointer); end
    def vi_big_backward_word(line, byte_pointer); end
    def vi_big_forward_end_word(line, byte_pointer); end
    def vi_big_forward_word(line, byte_pointer); end
    def vi_first_print(line); end
    def vi_forward_end_word(line, byte_pointer); end
    def vi_forward_word(line, byte_pointer, drop_terminate_spaces = T.unsafe(nil)); end
  end
end

Reline::Unicode::CSI_REGEXP = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::CSI_REGEXP_INDEX = T.let(T.unsafe(nil), Integer)
class Reline::Unicode::EastAsianWidth; end
Reline::Unicode::EastAsianWidth::TYPE_A = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::EastAsianWidth::TYPE_F = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::EastAsianWidth::TYPE_H = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::EastAsianWidth::TYPE_N = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::EastAsianWidth::TYPE_NA = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::EastAsianWidth::TYPE_W = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::EscapedChars = T.let(T.unsafe(nil), Array)
Reline::Unicode::EscapedPairs = T.let(T.unsafe(nil), Hash)
Reline::Unicode::GRAPHEME_CLUSTER_INDEX = T.let(T.unsafe(nil), Integer)
Reline::Unicode::MBCharWidthRE = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::NON_PRINTING_END = T.let(T.unsafe(nil), String)
Reline::Unicode::NON_PRINTING_END_INDEX = T.let(T.unsafe(nil), Integer)
Reline::Unicode::NON_PRINTING_START = T.let(T.unsafe(nil), String)
Reline::Unicode::NON_PRINTING_START_INDEX = T.let(T.unsafe(nil), Integer)
Reline::Unicode::OSC_REGEXP = T.let(T.unsafe(nil), Regexp)
Reline::Unicode::OSC_REGEXP_INDEX = T.let(T.unsafe(nil), Integer)
Reline::Unicode::WIDTH_SCANNER = T.let(T.unsafe(nil), Regexp)
Reline::VERSION = T.let(T.unsafe(nil), String)
