---
integration: rspec

includes:
  - lib

requires:
  - muina

matcher:
  subjects:
    - Muina::Action*
    - Muina::Action::ParamsFactory*
    - Muina::Action::Step*
    - Muina::Action::Step::Command*
    - Muina::Action::Step::Failure*
    - Muina::Action::Step::Query*
    - Muina::Action::Step::Result*
    - Muina::Any*
    - Muina::Classes*
    - Muina::Error*
    - Muina::TestError*
    - Muina::Parameters*
    - Muina::Params*
    - Muina::PrivateCreation*
    - Muina::Result*
    - Muina::Result::Factory*
    - Muina::Result::Failure*
    - Muina::Result::Null*
    - Muina::Result::Success*
    - Muina::Service*
    - Muina::SymbolHash*
    - Muina::Unit*
    - Muina::UNIT*
    - Muina::UntypedArray*
    - Muina::UntypedHash*
    - Muina::Utils*
    - Muina::Value*
    - Muina::VERSION*
