---
integration: rspec

includes:
  - lib

requires:
  - muina

matcher:
  subjects:
    - Muina::Action*
    - Muina::Action::Query*
    - Muina::Action::Step*
    - Muina::Classes*
    - Muina::Error*
    - Muina::TestError*
    - Muina::Params*
    - Muina::PrivateCreation*
    - Muina::Result*
    - Muina::Service*
    - Muina::Unit*
    - Muina::UNIT*
    - Muina::Utils*
    - Muina::Value*
    - Muina::VERSION*
