# typed: strict
# frozen_string_literal: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `bin/tapioca require`.

require 'action_controller'
require 'action_controller/metal/exceptions'
require 'byebug'
require 'muina/module'
require 'simplecov'
require 'sorbet-rails/typed_params'
require 'sorbet-runtime'
require 'sorbet-struct-comparable'
require 'zeitwerk'
