#!/usr/bin/env ruby
# typed: strict
# frozen_string_literal: true

require 'fileutils'
require_relative '../lib/muina/version'

src = File.expand_path("#{File.dirname(__FILE__)}/../rbi/muina.rbi")
dst = File.expand_path("#{Dir.pwd}/sorbet/rbi/gems/muina@#{Muina::VERSION}.rbi")

FileUtils.cp src, dst
